name: learn_dbt

profile: learn_dbt

seed-paths: ["seeds"]
model-paths: ["models", "test_models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  learn_dbt:
    +schema: raw

models:
  learn_dbt:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    marts:
      +materialized: table
    models_dir_test:
      +materialized: view
    models_dir_test2:
      +materialized: view
    materialized:
      +materialized: table
